### ISSUE TITLE
PLEASE ADD RANK USER

### ISSUE THREAD

**Issue by davelimbauan** [Tomato6966/better-discord-ranking-system#5]
I am new with coding bots and I am so happy to see this coding for leveling bots, I just don't understand what is needed for a user to get the rank card because it always say "PLEASE ADD RANK USER" after the command is inputted. Do I need to change something? Do I need to add something? Btw the additional codes that is being pinned how do I put it? 

Hope you understand and kindly guide me. Btw I'm so honored and proud to use your codes! Thank you.

**Comment by Tomato6966** [comment]
let user = message.mentions.users.first();
rank(user)
